site_name: Implementação Data Lakehouse
site_description: Projeto hands-on com Spark, Iceberg, MinIO e Jupyter
theme:
  name: material
  language: pt
  palette:
    scheme: slate
    primary: blue
    accent: cyan
  features:
    - navigation.tabs
    - content.code.copy
    - navigation.top

nav:
  - Início: index.md
  - Guia:
      - Instalação: instalacao.md
      - Execução: execucao.md
  - Tecnologias: tecnologias.md
  - Referencias: referencias.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
